[package]
name = "zagreus-server"
version = "0.0.4"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2018"

[dependencies]
log = "0.4.11"
futures = "0.3.15"
hyper = "0.14.9"
rand = "0.8.4"
serde = "1.0.126"
serde_derive = "1.0.126"
serde_json = "1.0.64"
tokio = { version = "1.7.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.6"
warp = "0.3.1"
zip = "0.5.13"

[dependencies.log4rs]
version = "1.0.0"
default-features = false
features = ["console_appender", "rolling_file_appender", "fixed_window_roller", "size_trigger", "compound_policy"]

[dev-dependencies]
tokio-tungstenite = "0.14.0"
tungstenite = "0.13.0"
