[package]
name = "zagreus-server"
version = "0.0.9"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2021"

[dependencies]
anyhow = "1.0.71"
axum = { version = "0.6.18", features = ["json", "http1", "http2", "ws", "multipart"]}
axum-server = "0.5.0"
log = "0.4.17"
futures = "0.3.28"
hyper = "0.14.26"
rand = "0.8.5"
serde = "1.0.163"
serde_derive = "1.0.163"
serde_json = "1.0.96"
structopt = "0.3.26"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.14"
tower = { version = "0.4.13", features = ["filter"]}
tower-http = { version = "0.4.0", features = ["fs", "trace"]}
zip = "0.6.5"
sha2 = "0.10.6"

[dependencies.log4rs]
version = "1.2.0"
default-features = false
features = ["console_appender", "rolling_file_appender", "fixed_window_roller", "size_trigger", "compound_policy", "json_encoder"]

[dev-dependencies]
tokio-tungstenite = "0.18.0"
tungstenite = "0.19.0"
